export const DRIVER_BY_CODE = {
  'HND-AR002': 'Sana Ullah',
  'HND-AR003': 'Muhammad Raheel Arshad',
  'HND-AR004': 'Tanveer Ahmad',
  'HND-AR005': 'Muhammad Niaz',
  'HND-CR001': 'Muhammad Asif',
  'HND-CT001': 'Asad Ali',
  'HND-CT003': 'Ahmad Hussain',
  'HND-CT004': 'Amjad Hussain',
  'HND-CT005': 'Faisal Muneer',
  'HND-CT006': 'Waseem Saleem',
  'HND-DR001': 'Muhammad Irfan',
  'HND-DT003': 'Maqsood',
  'HND-DT005': 'Muhammad Nawaz',
  'HND-DT1002': 'Khalid Razzaq',
  'HND-DT1003': 'Asif Hussain',
  'HND-DT1007': 'Muhammad Asif',
  'HND-DT1008': 'Salman Ahmad',
  'HND-FB001': 'Abdul Basit',
  'HND-FL001': 'Asad Raza',
  'HND-FL002': 'Muhammad Razzaq',
  'HND-FL004': 'Yasir Abbas',
  'HND-FL005': 'Muhammad Naeem Akhtar',
  'HND-FL006': 'Muhammad Waqas',
  'HND-FL007': 'Dilawar Hussain',
  'HND-FL008': 'Khan Muhammad',
  'HND-FL010': 'Irshad Ahmad',
  'HND-FL012': 'Muhammad Razaq',
  'HND-FL013': 'Sajjad',
  'HND-FL014': 'Malik Ali',
  'HND-FL015': 'Munawar Hussain',
  'HND-FL016': 'Mohsin Ali',
  'HND-FL017': 'Abdul Jawad',
  'HND-FL018': 'Basharat Ali',
  'HND-LR001': 'Shafqat Nadeem',
  'HND-LR002': 'Liaquat Ali',
  'HND-LR003': 'Muhammad Naveed',
  'HND-LR004': 'Ali Ahmad',
  'HND-LR005': 'Abdul Jabbar',
  'HND-LR006': 'Muhammad Hafeez',
  'HND-LR007': 'Salamat Ali',
  'HND-LR008': 'Muhammad Asif',
  'HND-LR009': 'Imtiaz Ali',
  'HND-LR010': 'Khalil Ahmad',
  'HND-LR011': 'Nazir Ahmad',
  'HND-LR012': 'Javed Iqbal',
  'HND-LR013': 'Abdul Rous',
  'HND-LR014': 'Muhammad Rashid Iqbal',
  'HND-LR015': 'Abdul Razzaq',
  'HND-LR016': 'Ali Akbar',
  'HND-LR017': 'Shahid Mahmood',
  'HND-LR018': 'Muhammad Mudassir',
  'HND-LR019': 'Muhammad Sarwar',
  'HND-LR020': 'Arsham Haider',
  'HND-LR021': 'Umar Sultan',
  'HND-LR022': 'Muhammad Tahreem',
  'HND-LR023': 'Amir Shahzad',
  'HND-LR024': 'Muhammad Ahmad',
  'HND-LR025': 'Sher Ali',
  'HND-LR026': 'Abrar Hussain',
  'HND-LR027': 'Saqib Ali',
  'HND-LR028': 'Mubashar Nadeem',
  'HND-LR029': 'Nasrullah',
  'HND-LR030': 'Muhammad Shahbaz',
  'HND-LR031': 'Ali Raza',
  'HND-LR032': 'Muhammad Latif',
  'HND-LR033': 'Abdul Rehman',
  'HND-LR034': 'Abdul Rehman',
  'HND-LR035': 'Hamza Khursheed',
  'HND-LR036': 'Muhammad Rasheed',
  'HND-LR037': 'Muhammad Sahil Saleem',
  'HND-LR038': 'Muhammad Tahir',
  'HND-LR039': 'Gull Zaman',
  'HND-LR040': 'Muhammad Ayoub',
  'HND-LR041': 'Muhammad Habib',
  'HND-LR042': 'Muhammad Ishaq',
  'HND-LR043': 'Abdul Majeed',
  'HND-LR044': 'Muhammad Siddique',
  'HND-LR045': 'Asif Hussain',
  'HND-LR046': 'Ghazanfar Ali',
  'HND-LR047': 'Muhammad Ahmad',
  'HND-LR048': 'Muhammad Hanif',
  'HND-LR049': 'Ali Hassan',
  'HND-LR050': 'Saif Ur Rehman',
  'HND-LR051': 'Imran Javed',
  'HND-LR052': 'Muhammad Zahid Yasin',
  'HND-LR053': 'Fiaz Ahmad',
  'HND-LR054': 'Muhammad Hamid',
  'HND-LR055': 'Muhammad Jamil',
  'HND-LR056': 'Muhammad Wasim',
  'HND-LR057': 'Muhammad Yousaf',
  'HND-LR058': 'Sajjad Ali',
  'HND-LR059': 'Muhammad Aleem',
  'HND-LR060': 'Muhammad Sufyan',
  'HND-LR061': 'Muhammad Fiaz',
  'HND-LR062': 'Muhammad Naseer',
  'HND-LR063': 'Muhammad Usman',
  'HND-LR064': 'Muhammad Rehan',
  'HND-LR065': 'Kashif Masih',
  'HND-LR066': 'Ahsan Manzoor',
  'HND-LR067': 'Faisal Hussain',
  'HND-LR068': 'Allah Ditta',
  'HND-LR069': 'Bilal Ali',
  'HND-LR070': 'Nasir Mahmood',
  'HND-LR071': 'Sharafat Ali',
  'HND-LR072': 'Waqas Ali',
  'HND-LR073': 'Muhammad Waqas Javed',
  'HND-LR074': 'Ghulam Mustafa',
  'HND-LR075': 'Mohsin Mushtaq',
  'HND-LR076': 'Muhammad Ramzan',
  'HND-LR077': 'Muhammad Mudassir',
  'HND-LR078': 'Muhammad Jahan Zaib',
  'HND-LR079': 'Ghulam Fareed',
  'HND-LR080': 'Muhammad Asif',
  'HND-LR081': 'Muhammad Ahmad',
  'HND-LR082': 'Muhammad Bilal',
  'HND-LR083': 'Muhammad Adnan',
  'HND-LR084': 'Muhammad Talib',
  'HND-LR085': 'Ahmer Asif',
  'HND-LR086': 'Muhammad Husnain Bilal',
  'HND-LR087': 'Shah Rasool',
  'HND-LR088': 'Shah Nawaz',
  'HND-LR089': 'Muhammad Rashid',
  'HND-LR090': 'Arshad Ali',
  'HND-LR091': 'Muhammad Ameen',
  'HND-LR092': 'Akhter Ali',
  'HND-LR093': 'Zafar Ullah Shahzad',
  'HND-LR094': 'Ibrar Hussain',
  'HND-LR095': 'Danish Ali',
  'HND-LR096': 'Muhammad Waseem',
  'HND-LR097': 'Wali Muhammad',
  'HND-LR098': 'Muhammad Ramzan',
  'HND-LR099': 'Sharafat Ali',
  'HND-LR100': 'Ammar Rasheed',
  'HND-LR101': 'Abrar Ahmad',
  'HND-LR102': 'Fiaz Ahmad',
  'HND-LR103': 'Matloob Hussain',
  'HND-LR104': '#N/A',
  'HND-LR105': 'Muhammad Nadeem',
  'HND-LR106': 'Muhammad Naqash',
  'HND-MS001': 'Mushtaq',
  'HND-MT001': 'Sagheer Ahmad',
  'HND-MT002': 'Ali Raza',
  'HND-MT003': 'Muhammad Ashraf',
  'HND-MT004': 'Abid Mahmood',
  'HND-MT005': 'Syed Muhammad Mumtaz Shah',
  'HND-MT006': 'Ghulam Rabbani Hashmi',
  'HND-MT007': 'Ulfat Rasool',
  'HND-MT008': 'Ghulam Mustafa',
  'HND-MT009': 'Muhammad Shahzad Ali',
  'HND-MT011': 'Abdur Rahman Shoukat',
  'HND-MW001': 'Ali Raza',
  'HND-TT001': 'Muhammad Zahid Nadeem',
  'HND-TT002': 'Muhammad Ashraf',
  'HND-TT003': 'Muhammad Ahsan',
  'HND-TT004': 'Ghulam Mustafa',
  'HND-TT005': 'Muhammad Naseer',
  'HND-TT006': 'Jabar Ali',
  'HND-TT007': 'Muhammad Ahmad',
  'HND-TT008': 'Rameez Nazir',
  'HND-TT010': 'Noor khan',
  'HND-TT011': 'Muhammad Hanif',
  'HND-TT012': 'Ibrar Hussain',
  'HND-TT013': 'Zahoor Ahmad',
  'HND-TT014': 'Fakhar Haroon',
  'HND-TT015': 'Muhammad Shafqiue',
  'HND-TT016': 'Muhammad Rafique',
  'HND-TT017': 'Muhammad Arslan Akram',
  'HND-TT018': 'Muhammad Usman',
  'HND-TT019': 'Shahbaz Ahmad',
  'HND-TT020': 'Afzaal Ahmad',
  'HND-TT021': 'Abid Hussain',
  'HND-TT022': 'Muhammad Ismail',
  'HND-TT023': 'Muhammad Ishaq',
  'HND-TT024': 'Muhammad Mustafa',
  'HND-TT025': 'Abid Hussain',
  'HND-TT026': 'Mehmood Ahmad',
  'HND-TT027': 'Muhammad Ilyas',
  'HND-TT028': 'Qasir Abbas',
  'HND-TT029': 'Sami Ullah',
  'HND-WB001': 'Muhammad Idress',
}

export function driverOf(code) {
  return DRIVER_BY_CODE[code] ?? ''
}
