export const SUPERVISOR_BY_CODE = {
  'HND-AR002': 'Rao Waseem',
  'HND-AR003': 'Rao Waseem',
  'HND-AR004': 'Rao Waseem',
  'HND-AR005': 'Rao Waseem',
  'HND-CR001': 'Rao Waseem',
  'HND-CT001': 'Muhammad Hamza Javed',
  'HND-CT003': 'Rao Waseem',
  'HND-CT004': 'Rao Waseem',
  'HND-CT005': 'Rao Waseem',
  'HND-CT006': 'Rao Waseem',
  'HND-DR001': 'Rao Waseem',
  'HND-DT003': 'Rao Waseem',
  'HND-DT005': 'Rao Waseem',
  'HND-DT1002': 'Rao Waseem',
  'HND-DT1003': 'Rao Waseem',
  'HND-DT1007': 'Rao Waseem',
  'HND-DT1008': 'Rao Waseem',
  'HND-FB001': 'Rao Waseem',
  'HND-FL001': 'Muhammad Hamza Javed',
  'HND-FL002': 'Abrar Hussain',
  'HND-FL004': 'Muhamad Umar Farooq',
  'HND-FL005': 'Muhammad Waseem Irshad',
  'HND-FL006': 'Kehshan Manzoor',
  'HND-FL007': 'Nasir Mahmood',
  'HND-FL008': 'Rao Waseem',
  'HND-FL010': 'Muhammad Rizwan',
  'HND-FL012': 'Nouman Aftab',
  'HND-FL013': 'Muhammad Nasir',
  'HND-FL014': 'Rao Waseem',
  'HND-FL015': 'Muhammad Khalid Mahmood',
  'HND-FL016': 'Talha Abbas',
  'HND-FL017': 'Muhammad Rizwan Anjum',
  'HND-FL018': 'Muhammad Faizan',
  'HND-LR001': 'Umar Farooq',
  'HND-LR002': 'Muhammad Khalid Mahmood',
  'HND-LR003': 'Muhammad Rizwan Anjum',
  'HND-LR004': 'Muhammad Khalid Mahmood',
  'HND-LR005': 'Muhammad Akram',
  'HND-LR006': 'Nouman Aftab',
  'HND-LR007': 'Muhammad Hamza Javed',
  'HND-LR008': 'Muhammad Rizwan',
  'HND-LR009': 'Talha Abbas',
  'HND-LR010': 'Muhammad Hamza Javed',
  'HND-LR011': 'Muhammad Nasir',
  'HND-LR012': 'Nasir Mahmood',
  'HND-LR013': 'Muhammad Hamza Javed',
  'HND-LR014': 'Ansab Iqbal',
  'HND-LR015': 'Abrar Hussain',
  'HND-LR016': 'Muhammad Waqas',
  'HND-LR017': 'Ghulam Rabani',
  'HND-LR018': 'Muhammad Waqas',
  'HND-LR019': 'Muhammad Faizan',
  'HND-LR020': 'Ghulam Rabani',
  'HND-LR021': 'Muhamad Umar Farooq',
  'HND-LR022': 'Talha Raiz',
  'HND-LR023': 'Muhammad Waseem Irshad',
  'HND-LR024': 'Muhammad Huzafia',
  'HND-LR025': 'Kehshan Manzoor',
  'HND-LR026': 'Muhammad Rizwan',
  'HND-LR027': 'Arslan Arshid',
  'HND-LR028': 'Muhammad Rizwan',
  'HND-LR029': 'Syed Sajjad Shah',
  'HND-LR030': 'Kehshan Manzoor',
  'HND-LR031': 'Muhammad Waseem Irshad',
  'HND-LR032': 'Arslan Arshid',
  'HND-LR033': 'Muhammad Iftikhar Ali',
  'HND-LR034': 'Syed Sajjad Shah',
  'HND-LR035': 'Arslan Arshid',
  'HND-LR036': 'Muhammad Iftikhar Ali',
  'HND-LR037': 'Sagheer Hussain',
  'HND-LR038': 'Muhammad Shoaib Akhtar',
  'HND-LR039': 'Muhamad Umar Farooq',
  'HND-LR040': 'Muhammad Nasir',
  'HND-LR041': 'Muhammad Hamza Javed',
  'HND-LR042': 'Nasir Mahmood',
  'HND-LR043': 'Muhammad Shoaib Akhtar',
  'HND-LR044': 'Muhamad Umar Farooq',
  'HND-LR045': 'Sagheer Hussain',
  'HND-LR046': 'Sagheer Hussain',
  'HND-LR047': 'Nasir Mahmood',
  'HND-LR048': 'Nouman Aftab',
  'HND-LR049': 'Ansab Iqbal',
  'HND-LR050': 'Abrar Hussain',
  'HND-LR051': 'Talha Abbas',
  'HND-LR052': 'Muhammad Akram',
  'HND-LR053': 'Muhammad Rizwan Anjum',
  'HND-LR054': 'Nasir Mahmood',
  'HND-LR055': 'Sagheer Hussain',
  'HND-LR056': 'Muhammad Khalid Mahmood',
  'HND-LR057': 'Talha Abbas',
  'HND-LR058': 'Muhammad Rizwan Anjum',
  'HND-LR059': 'Talha Abbas',
  'HND-LR060': 'Muhammad Rizwan Anjum',
  'HND-LR061': 'Muhammad Safdar',
  'HND-LR062': 'Munawar Zaman',
  'HND-LR063': 'Muhammad Safdar',
  'HND-LR064': 'Muhammad Safdar',
  'HND-LR065': 'Munawar Zaman',
  'HND-LR066': 'Abrar Hussain',
  'HND-LR067': 'Muhammad Waqas',
  'HND-LR068': 'Asad Raza Mehdi',
  'HND-LR069': 'Asad Raza Mehdi',
  'HND-LR070': 'Asad Raza Mehdi',
  'HND-LR071': 'Muhammad Shoaib Akhtar',
  'HND-LR072': 'Muhammad Faizan',
  'HND-LR073': 'Ansab Iqbal',
  'HND-LR074': 'Muhammad Akram',
  'HND-LR075': 'Muhammad Faizan',
  'HND-LR076': 'Nouman Aftab',
  'HND-LR077': 'Nouman Aftab',
  'HND-LR078': 'Muhammad Waqas',
  'HND-LR079': 'Muhammad Faizan',
  'HND-LR080': 'Muhammad Nasir',
  'HND-LR081': 'Muhammad Nasir',
  'HND-LR082': 'Ghulam Rabani',
  'HND-LR083': 'Muhammad Akram',
  'HND-LR084': 'Asad Raza Mehdi',
  'HND-LR085': 'Muhammad Shoaib Akhtar',
  'HND-LR086': 'Muhammad Rizwan',
  'HND-LR087': 'Abdullah Shahid',
  'HND-LR088': 'Abdullah Shahid',
  'HND-LR089': 'Kehshan Manzoor',
  'HND-LR090': 'Muhammad Waseem Irshad',
  'HND-LR091': 'Muhammad Khalid Mahmood',
  'HND-LR092': 'Kehshan Manzoor',
  'HND-LR093': 'Muhamad Umar Farooq',
  'HND-LR094': 'Munawar Zaman',
  'HND-LR095': 'Abrar Hussain',
  'HND-LR096': 'Ansab Iqbal',
  'HND-LR097': 'Muhammad Waseem Irshad',
  'HND-LR098': 'Ghulam Rabani',
  'HND-LR099': 'Abdullah Shahid',
  'HND-LR100': 'Arslan Arshid',
  'HND-LR101': 'Muhammad Safdar',
  'HND-LR102': 'Abdullah Shahid',
  'HND-LR103': 'Munawar Zaman',
  'HND-LR104': '#N/A',
  'HND-LR105': 'Syed Sajjad Shah',
  'HND-LR106': 'Syed Sajjad Shah',
  'HND-MS001': 'Umar Farooq',
  'HND-MT001': 'Muhammad Huzafia',
  'HND-MT002': 'Talha Raiz',
  'HND-MT003': 'Nadeem Masih',
  'HND-MT004': 'Rajesh Kumar',
  'HND-MT005': 'Talha Raiz',
  'HND-MT006': 'Muhammad Huzafia',
  'HND-MT007': 'HidayatUllah khan',
  'HND-MT008': 'Rajesh Kumar',
  'HND-MT009': 'HidayatUllah khan',
  'HND-MT011': 'Rajesh Kumar',
  'HND-MW001': 'Rajesh Kumar',
  'HND-TT001': 'Asad Raza Mehdi',
  'HND-TT002': 'Muhammad Faizan',
  'HND-TT003': 'Muhammad Waseem Irshad',
  'HND-TT004': 'Rao Waseem',
  'HND-TT005': 'Muhammad Hamza Javed',
  'HND-TT006': 'Nasir Mahmood',
  'HND-TT007': 'Muhammad Shoaib Akhtar',
  'HND-TT008': 'Rao Waseem',
  'HND-TT010': 'Muhammad Rizwan',
  'HND-TT011': 'Muhammad Rizwan Anjum',
  'HND-TT012': 'Sagheer Hussain',
  'HND-TT013': 'Muhammad Akram',
  'HND-TT014': 'Munawar Zaman',
  'HND-TT015': 'Abrar Hussain',
  'HND-TT016': 'Talha Abbas',
  'HND-TT017': 'Muhammad Safdar',
  'HND-TT018': 'Muhammad Nasir',
  'HND-TT019': 'Ansab Iqbal',
  'HND-TT020': 'Nouman Aftab',
  'HND-TT021': 'Ghulam Rabani',
  'HND-TT022': 'Muhammad Waqas',
  'HND-TT023': 'Muhammad Khalid Mahmood',
  'HND-TT024': 'Kehshan Manzoor',
  'HND-TT025': 'Syed Sajjad Shah',
  'HND-TT026': 'Abdullah Shahid',
  'HND-TT027': 'Arslan Arshid',
  'HND-TT028': 'Muhamad Umar Farooq',
  'HND-TT029': 'Rao Waseem',
  'HND-WB001': 'Rao Waseem',
}

export function supervisorOf(code) {
  return SUPERVISOR_BY_CODE[code] ?? ''
}
