export const USED_FOR_BY_CODE = {
  'HND-AR002': 'Container-Based Collection',
  'HND-AR003': 'Container-Based Collection',
  'HND-AR004': 'Container-Based Collection',
  'HND-AR005': 'Container-Based Collection',
  'HND-CR001': 'Container-Repair Vehicle',
  'HND-CT001': 'Container-Based Collection',
  'HND-CT003': 'Container-Based Collection',
  'HND-CT004': 'Container-Based Collection',
  'HND-CT005': 'Container-Based Collection',
  'HND-CT006': 'Container-Based Collection',
  'HND-DR001': 'Drain Cleaner',
  'HND-DT003': 'TCP Fleet',
  'HND-DT005': 'TCP Fleet',
  'HND-DT1002': 'TCP Fleet',
  'HND-DT1003': 'Landfill Site Fleet',
  'HND-DT1007': 'TCP Fleet',
  'HND-DT1008': 'TCP Fleet',
  'HND-FB001': 'TCP Fleet',
  'HND-FL001': 'TCP Fleet',
  'HND-FL002': 'TCP Fleet',
  'HND-FL004': 'TCP Fleet',
  'HND-FL005': 'Bulk Waste Collection',
  'HND-FL006': 'Bulk Waste Collection',
  'HND-FL007': 'TCP Fleet',
  'HND-FL008': 'Landfill Site Fleet',
  'HND-FL010': 'Bulk Waste Collection',
  'HND-FL012': 'TCP Fleet',
  'HND-FL013': 'TCP Fleet',
  'HND-FL014': 'Landfill Site Fleet',
  'HND-FL015': 'TCP Fleet',
  'HND-FL016': 'TCP Fleet',
  'HND-FL017': 'TCP Fleet',
  'HND-FL018': 'Bulk Waste Collection',
  'HND-LR001': 'Door To Door Collection',
  'HND-LR002': 'Door To Door Collection',
  'HND-LR003': 'Door To Door Collection',
  'HND-LR004': 'Door To Door Collection',
  'HND-LR005': 'Door To Door Collection',
  'HND-LR006': 'Door To Door Collection',
  'HND-LR007': 'Door To Door Collection',
  'HND-LR008': 'Commercial',
  'HND-LR009': 'Door To Door Collection',
  'HND-LR010': 'Door To Door Collection',
  'HND-LR011': 'Door To Door Collection',
  'HND-LR012': 'Commercial',
  'HND-LR013': 'Commercial',
  'HND-LR014': 'Commercial',
  'HND-LR015': 'Commercial',
  'HND-LR016': 'Door To Door Collection',
  'HND-LR017': 'Door To Door Collection',
  'HND-LR018': 'Door To Door Collection',
  'HND-LR019': 'Door To Door Collection',
  'HND-LR020': 'Commercial',
  'HND-LR021': 'Commercial',
  'HND-LR022': 'Door To Door Collection',
  'HND-LR023': 'Door To Door Collection',
  'HND-LR024': 'Door To Door Collection',
  'HND-LR025': 'Door To Door Collection',
  'HND-LR026': 'Door To Door Collection',
  'HND-LR027': 'Door To Door Collection',
  'HND-LR028': 'Door To Door Collection',
  'HND-LR029': 'Commercial',
  'HND-LR030': 'Commercial',
  'HND-LR031': 'Commercial',
  'HND-LR032': 'Door To Door Collection',
  'HND-LR033': 'Commercial',
  'HND-LR034': 'Door To Door Collection',
  'HND-LR035': 'Commercial',
  'HND-LR036': 'Commercial',
  'HND-LR037': 'Commercial',
  'HND-LR038': 'Commercial',
  'HND-LR039': 'Door To Door Collection',
  'HND-LR040': 'Door To Door Collection',
  'HND-LR041': 'Door To Door Collection',
  'HND-LR042': 'Commercial',
  'HND-LR043': 'Commercial',
  'HND-LR044': 'Door To Door Collection',
  'HND-LR045': 'Door To Door Collection',
  'HND-LR046': 'Commercial',
  'HND-LR047': 'Door To Door Collection',
  'HND-LR048': 'Commercial',
  'HND-LR049': 'Commercial',
  'HND-LR050': 'Commercial',
  'HND-LR051': 'Commercial',
  'HND-LR052': 'Commercial',
  'HND-LR053': 'Commercial',
  'HND-LR054': 'De-Silting',
  'HND-LR055': 'Door To Door Collection',
  'HND-LR056': 'Door To Door Collection',
  'HND-LR057': 'Door To Door Collection',
  'HND-LR058': 'Door To Door Collection',
  'HND-LR059': 'Door To Door Collection',
  'HND-LR060': 'Door To Door Collection',
  'HND-LR061': 'Door To Door Collection',
  'HND-LR062': 'Door To Door Collection',
  'HND-LR063': 'Door To Door Collection',
  'HND-LR064': 'Door To Door Collection',
  'HND-LR065': 'Door To Door Collection',
  'HND-LR066': 'Door To Door Collection',
  'HND-LR067': 'Commercial',
  'HND-LR068': 'Commercial',
  'HND-LR069': 'Commercial',
  'HND-LR070': 'Commercial',
  'HND-LR071': 'Door To Door Collection',
  'HND-LR072': 'Door To Door Collection',
  'HND-LR073': 'Commercial',
  'HND-LR074': 'Commercial',
  'HND-LR075': 'Commercial',
  'HND-LR076': 'Commercial',
  'HND-LR077': 'Door To Door Collection',
  'HND-LR078': 'Door To Door Collection',
  'HND-LR079': 'Door To Door Collection',
  'HND-LR080': 'Door To Door Collection',
  'HND-LR081': 'Door To Door Collection',
  'HND-LR082': 'Door To Door Collection',
  'HND-LR083': 'Door To Door Collection',
  'HND-LR084': 'Door To Door Collection',
  'HND-LR085': 'Door To Door Collection',
  'HND-LR086': 'Door To Door Collection',
  'HND-LR087': 'Door To Door Collection',
  'HND-LR088': 'Door To Door Collection',
  'HND-LR089': 'Commercial',
  'HND-LR090': 'Commercial',
  'HND-LR091': 'Door To Door Collection',
  'HND-LR092': 'Commercial',
  'HND-LR093': 'Door To Door Collection',
  'HND-LR094': 'Door To Door Collection',
  'HND-LR095': 'Door To Door Collection',
  'HND-LR096': 'Commercial',
  'HND-LR097': 'Commercial',
  'HND-LR098': 'Commercial',
  'HND-LR099': 'Commercial',
  'HND-LR100': 'Commercial',
  'HND-LR101': 'Commercial',
  'HND-LR102': 'Commercial',
  'HND-LR103': 'Commercial',
  'HND-LR104': '',
  'HND-LR105': 'Door To Door Collection',
  'HND-LR106': 'Commercial',
  'HND-MS001': 'Sweeping',
  'HND-MT001': 'Commercial',
  'HND-MT002': 'Commercial',
  'HND-MT003': 'Commercial',
  'HND-MT004': 'Commercial',
  'HND-MT005': 'Commercial',
  'HND-MT006': 'Commercial',
  'HND-MT007': 'Commercial',
  'HND-MT008': 'Commercial',
  'HND-MT009': 'Commercial',
  'HND-MT011': 'Commercial',
  'HND-MW001': 'Washing',
  'HND-TT001': 'TCP Fleet',
  'HND-TT002': 'Bulk Waste Collection',
  'HND-TT003': 'TCP Fleet',
  'HND-TT004': 'Bulk Waste Collection',
  'HND-TT005': 'TCP Fleet',
  'HND-TT006': 'Bulk Waste Collection',
  'HND-TT007': 'Bulk Waste Collection',
  'HND-TT008': 'Bulk Waste Collection',
  'HND-TT010': 'Bulk Waste Collection',
  'HND-TT011': 'Bulk Waste Collection',
  'HND-TT012': 'TCP Fleet',
  'HND-TT013': 'TCP Fleet',
  'HND-TT014': 'TCP Fleet',
  'HND-TT015': 'TCP Fleet',
  'HND-TT016': 'TCP Fleet',
  'HND-TT017': 'TCP Fleet',
  'HND-TT018': 'TCP Fleet',
  'HND-TT019': 'TCP Fleet',
  'HND-TT020': 'TCP Fleet',
  'HND-TT021': 'TCP Fleet',
  'HND-TT022': 'TCP Fleet',
  'HND-TT023': 'TCP Fleet',
  'HND-TT024': 'TCP Fleet',
  'HND-TT025': 'Bulk Waste Collection',
  'HND-TT026': 'TCP Fleet',
  'HND-TT027': 'Bulk Waste Collection',
  'HND-TT028': 'TCP Fleet',
  'HND-TT029': 'TCP Fleet',
  'HND-WB001': 'Washing',
}

export function usedForOf(code) {
  return USED_FOR_BY_CODE[code] ?? ''
}
