export const VEHICLE_TYPES = {
  'HND-AR002': 'Arm Roller',
  'HND-AR003': 'Arm Roller',
  'HND-AR004': 'Arm Roller',
  'HND-AR005': 'Arm Roller',
  'HND-CR001': 'Container-Repair Vehicle',
  'HND-CT001': 'Compactor',
  'HND-CT003': 'Compactor',
  'HND-CT004': 'Compactor',
  'HND-CT005': 'Compactor',
  'HND-CT006': 'Compactor',
  'HND-DR001': 'Drain Cleaner',
  'HND-DT003': 'Dumper',
  'HND-DT005': 'Dumper',
  'HND-DT1002': 'Dumper',
  'HND-DT1003': 'Dumper',
  'HND-DT1007': 'Dumper',
  'HND-DT1008': 'Dumper',
  'HND-FB001': 'Front Blade Tractor',
  'HND-FL001': 'Front End Loader',
  'HND-FL002': 'Front End Loader',
  'HND-FL004': 'Front End Loader',
  'HND-FL005': 'Front End Loader',
  'HND-FL006': 'Front End Loader',
  'HND-FL007': 'Front End Loader',
  'HND-FL008': 'Front End Loader',
  'HND-FL010': 'Front End Loader',
  'HND-FL012': 'Front End Loader',
  'HND-FL013': 'Front End Loader',
  'HND-FL014': 'Front End Loader',
  'HND-FL015': 'Front End Loader',
  'HND-FL016': 'Front End Loader',
  'HND-FL017': 'Front End Loader',
  'HND-FL018': 'Front End Loader',
  'HND-LR001': 'Loader Rickshaw',
  'HND-LR002': 'Loader Rickshaw',
  'HND-LR003': 'Loader Rickshaw',
  'HND-LR004': 'Loader Rickshaw',
  'HND-LR005': 'Loader Rickshaw',
  'HND-LR006': 'Loader Rickshaw',
  'HND-LR007': 'Loader Rickshaw',
  'HND-LR008': 'Loader Rickshaw',
  'HND-LR009': 'Loader Rickshaw',
  'HND-LR010': 'Loader Rickshaw',
  'HND-LR011': 'Loader Rickshaw',
  'HND-LR012': 'Loader Rickshaw',
  'HND-LR013': 'Loader Rickshaw',
  'HND-LR014': 'Loader Rickshaw',
  'HND-LR015': 'Loader Rickshaw',
  'HND-LR016': 'Loader Rickshaw',
  'HND-LR017': 'Loader Rickshaw',
  'HND-LR018': 'Loader Rickshaw',
  'HND-LR019': 'Loader Rickshaw',
  'HND-LR020': 'Loader Rickshaw',
  'HND-LR021': 'Loader Rickshaw',
  'HND-LR022': 'Loader Rickshaw',
  'HND-LR023': 'Loader Rickshaw',
  'HND-LR024': 'Loader Rickshaw',
  'HND-LR025': 'Loader Rickshaw',
  'HND-LR026': 'Loader Rickshaw',
  'HND-LR027': 'Loader Rickshaw',
  'HND-LR028': 'Loader Rickshaw',
  'HND-LR029': 'Loader Rickshaw',
  'HND-LR030': 'Loader Rickshaw',
  'HND-LR031': 'Loader Rickshaw',
  'HND-LR032': 'Loader Rickshaw',
  'HND-LR033': 'Loader Rickshaw',
  'HND-LR034': 'Loader Rickshaw',
  'HND-LR035': 'Loader Rickshaw',
  'HND-LR036': 'Loader Rickshaw',
  'HND-LR037': 'Loader Rickshaw',
  'HND-LR038': 'Loader Rickshaw',
  'HND-LR039': 'Loader Rickshaw',
  'HND-LR040': 'Loader Rickshaw',
  'HND-LR041': 'Loader Rickshaw',
  'HND-LR042': 'Loader Rickshaw',
  'HND-LR043': 'Loader Rickshaw',
  'HND-LR044': 'Loader Rickshaw',
  'HND-LR045': 'Loader Rickshaw',
  'HND-LR046': 'Loader Rickshaw',
  'HND-LR047': 'Loader Rickshaw',
  'HND-LR048': 'Loader Rickshaw',
  'HND-LR049': 'Loader Rickshaw',
  'HND-LR050': 'Loader Rickshaw',
  'HND-LR051': 'Loader Rickshaw',
  'HND-LR052': 'Loader Rickshaw',
  'HND-LR053': 'Loader Rickshaw',
  'HND-LR054': 'Loader Rickshaw',
  'HND-LR055': 'Loader Rickshaw',
  'HND-LR056': 'Loader Rickshaw',
  'HND-LR057': 'Loader Rickshaw',
  'HND-LR058': 'Loader Rickshaw',
  'HND-LR059': 'Loader Rickshaw',
  'HND-LR060': 'Loader Rickshaw',
  'HND-LR061': 'Loader Rickshaw',
  'HND-LR062': 'Loader Rickshaw',
  'HND-LR063': 'Loader Rickshaw',
  'HND-LR064': 'Loader Rickshaw',
  'HND-LR065': 'Loader Rickshaw',
  'HND-LR066': 'Loader Rickshaw',
  'HND-LR067': 'Loader Rickshaw',
  'HND-LR068': 'Loader Rickshaw',
  'HND-LR069': 'Loader Rickshaw',
  'HND-LR070': 'Loader Rickshaw',
  'HND-LR071': 'Loader Rickshaw',
  'HND-LR072': 'Loader Rickshaw',
  'HND-LR073': 'Loader Rickshaw',
  'HND-LR074': 'Loader Rickshaw',
  'HND-LR075': 'Loader Rickshaw',
  'HND-LR076': 'Loader Rickshaw',
  'HND-LR077': 'Loader Rickshaw',
  'HND-LR078': 'Loader Rickshaw',
  'HND-LR079': 'Loader Rickshaw',
  'HND-LR080': 'Loader Rickshaw',
  'HND-LR081': 'Loader Rickshaw',
  'HND-LR082': 'Loader Rickshaw',
  'HND-LR083': 'Loader Rickshaw',
  'HND-LR084': 'Loader Rickshaw',
  'HND-LR085': 'Loader Rickshaw',
  'HND-LR086': 'Loader Rickshaw',
  'HND-LR087': 'Loader Rickshaw',
  'HND-LR088': 'Loader Rickshaw',
  'HND-LR089': 'Loader Rickshaw',
  'HND-LR090': 'Loader Rickshaw',
  'HND-LR091': 'Loader Rickshaw',
  'HND-LR092': 'Loader Rickshaw',
  'HND-LR093': 'Loader Rickshaw',
  'HND-LR094': 'Loader Rickshaw',
  'HND-LR095': 'Loader Rickshaw',
  'HND-LR096': 'Loader Rickshaw',
  'HND-LR097': 'Loader Rickshaw',
  'HND-LR098': 'Loader Rickshaw',
  'HND-LR099': 'Loader Rickshaw',
  'HND-LR100': 'Loader Rickshaw',
  'HND-LR101': 'Loader Rickshaw',
  'HND-LR102': 'Loader Rickshaw',
  'HND-LR103': 'Loader Rickshaw',
  'HND-LR104': 'Loader Rickshaw',
  'HND-LR105': 'Loader Rickshaw',
  'HND-LR106': 'Loader Rickshaw',
  'HND-MS001': 'Mechanical Sweeper',
  'HND-MT001': 'Mini Tipper Petrol',
  'HND-MT002': 'Mini Tipper Petrol',
  'HND-MT003': 'Mini Tipper Petrol',
  'HND-MT004': 'Mini Tipper Petrol',
  'HND-MT005': 'Mini Tipper Petrol',
  'HND-MT006': 'Mini Tipper Petrol',
  'HND-MT007': 'Mini Tipper Petrol',
  'HND-MT008': 'Mini Tipper Petrol',
  'HND-MT009': 'Mini Tipper Petrol',
  'HND-MT011': 'Mini Tipper Petrol',
  'HND-MW001': 'Road Washer',
  'HND-TT001': 'Tractor Trolley',
  'HND-TT002': 'Tractor Trolley',
  'HND-TT003': 'Tractor Trolley',
  'HND-TT004': 'Tractor Trolley',
  'HND-TT005': 'Tractor Trolley',
  'HND-TT006': 'Tractor Trolley',
  'HND-TT007': 'Tractor Trolley',
  'HND-TT008': 'Tractor Trolley',
  'HND-TT010': 'Tractor Trolley',
  'HND-TT011': 'Tractor Trolley',
  'HND-TT012': 'Tractor Trolley',
  'HND-TT013': 'Tractor Trolley',
  'HND-TT014': 'Tractor Trolley',
  'HND-TT015': 'Tractor Trolley',
  'HND-TT016': 'Tractor Trolley',
  'HND-TT017': 'Tractor Trolley',
  'HND-TT018': 'Tractor Trolley',
  'HND-TT019': 'Tractor Trolley',
  'HND-TT020': 'Tractor Trolley',
  'HND-TT021': 'Tractor Trolley',
  'HND-TT022': 'Tractor Trolley',
  'HND-TT023': 'Tractor Trolley',
  'HND-TT024': 'Tractor Trolley',
  'HND-TT025': 'Tractor Trolley',
  'HND-TT026': 'Tractor Trolley',
  'HND-TT027': 'Tractor Trolley',
  'HND-TT028': 'Tractor Trolley',
  'HND-TT029': 'Tractor Trolley',
  'HND-WB001': 'Road Washer',
}

export function vehicleTypeOf(code) {
  return VEHICLE_TYPES[code] ?? ''
}
